#!/usr/bin/env bash

docker pull apsu/devcontainer
docker image prune -f
docker run --platform=linux/amd64 --volume ~/.ssh:/home/dev/.ssh --name devcontainer apsu/devcontainer 2>/dev/null
docker start --interactive --attach devcontainer
