#!/usr/bin/env bash

out=$(docker pull apsu/devcontainer)
if [[ $out != *"up to date"* ]] || ! docker ps -a | grep devcontainer; then
    docker stop devcontainer
    docker rm -f devcontainer
    docker image prune -f
    docker run --detach --interactive --tty --platform=linux/amd64 --volume ~/.ssh:/home/dev/.ssh --name devcontainer apsu/devcontainer
fi
docker start --interactive --attach devcontainer
