#!/usr/bin/env bash

docker pull apsu/devcontainer
docker image prune -f
docker run --detach --interactive --tty --platform=linux/amd64 --volume ~/.ssh:/home/dev/.ssh --name devcontainer apsu/devcontainer
docker start --interactive --attach devcontainer
